### ISSUE TITLE
Remove `rust-toolchain` file

### ISSUE THREAD

**Issue by adoerr** [facebookincubator/superconsole#3]
I do understand that using `superconsole` strictly as a dependency, I'm not really affected by the toolchain file.

My grumble is more on the QA side of things. Looks like the requirement for a pinned nightly version comes from some Meta internal CI or something. That `rust-toolchain` file kind of indicates, that `superconsole` is basically never build with current `stable`, no?

So, for the public `superconsole` repo, I think, the toolchain file should either be removed or use the `stable` channel.

**Comment by ndmitchell** [comment]
For QA, the actual CI is run with nightly overriding whatever is in the rust-toolchain file. https://github.com/facebookincubator/superconsole/blob/main/.github/workflows/ci.yml#L20-L22. I know at some point in earlier development that superconsole required a few nightly features, which were removed in order to make it more open source friendly. It seems pretty sensible to also remove the rust-toolchain file, and test with the stable toolchain during CI. The reason this exists is probably because of copying a different Meta project that does require nightly, there's no Meta requirement for it to look the way it does.

CC @abrassel who probably copied/created that file in the first place.

**Comment by abrassel** [comment]
@adoerr Thank you for pointing this out!  I've gone ahead and removed the toolchain file.
